apiVersion: v1
kind: ConfigMap
metadata: { name: voom-prom-scrape, namespace: voom }
data:
  scrape.yml: |
    scrape_configs:
    - job_name: 'gateway'
      static_configs: [ { targets: ['gateway:8080'] } ]