name: docker
on:
  push:
    branches: [ main ]
jobs:
  images:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with: { registry: ghcr.io, username: ${{ github.actor }}, password: ${{ secrets.GITHUB_TOKEN }} }
      - name: Build and push
        run: |
          docker build -t ghcr.io/${{ github.repository }}/optimizer:latest -f deploy/docker/cpp.Dockerfile .
          docker push ghcr.io/${{ github.repository }}/optimizer:latest
          docker build -t ghcr.io/${{ github.repository }}/ml-eta:latest -f deploy/docker/python.Dockerfile .
          docker push ghcr.io/${{ github.repository }}/ml-eta:latest
          docker build -t ghcr.io/${{ github.repository }}/gateway:latest -f deploy/docker/go.Dockerfile .
          docker push ghcr.io/${{ github.repository }}/gateway:latest